

# Run all executable scripts in given directory
run_scripts() {
    for script in $1/*; do

        # skip non-executable snippets
        [ -x "$script" ] || continue

        # execute $script in the context of the current shell
        . $script
    done
}

# Source all files in .bahshrc.d if exist
if [ -d $HOME/.bashrc.d ]; then
    run_scripts $HOME/.bashrc.d
fi

# Source local bashrc if there
if [ -f $HOME/.bashrc.local ]; then
    source $HOME/.bashrc.local
fi
